{% set name = "b3sum" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6b51aefe515969785da02e87befafc7fdc7a065cd3458cf1141f29267749e81f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - b3sum --help

about:
  home: https://github.com/BLAKE3-team/BLAKE3
  summary: 'A command line utility for calculating BLAKE3 hashes. '
  description: |
    A command line utility for calculating BLAKE3 hashes, 
    similar to Coreutils tools like b2sum or md5sum.  
  license: CC0-1.0
  license_file:
    - LICENSE_A2
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - maarten-k
