{% set name = "b3sum" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1f2fbd93790694f1ad66eef26e23c42260a1916927184d78d8395ff1a512d285

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - b3sum --help

about:
  home: https://github.com/BLAKE3-team/BLAKE3
  summary: 'A command line utility for calculating BLAKE3 hashes. '
  description: |
    A command line utility for calculating BLAKE3 hashes, 
    similar to Coreutils tools like b2sum or md5sum.  
  license: CC0-1.0
  license_file:
    - LICENSE_A2
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - maarten-k
