{% set name = "b3sum" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1bc38cd3cc501458054c3bb473e5e00338d6175121424040079025ea305ddef3


build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - cargo-bundle-licenses

test:
  commands:
    - b3sum --help

about:
  home: https://github.com/BLAKE3-team/BLAKE3
  summary: 'A command line utility for calculating BLAKE3 hashes. '
  description: |
    A command line utility for calculating BLAKE3 hashes, 
    similar to Coreutils tools like b2sum or md5sum.  
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - maarten-k
